const Prods = [
    {
        id: 1,
        title: "boAt Bassheads 100 in Ear Wired Earphones with Mic(Black)",
        price: 299,
        rating: "4",
        img: "https://m.media-amazon.com/images/I/719elVA3FvL._AC_UL640_QL65_.jpg",
        inCart: 0,
    },
    {
        id: 2,
        title: "Amazon Brand - Solimo XXXL Faux Leather Bean Bag Filled With Beans (Black and Brown)",
        price: 1299,
        rating: "2",
        img: "https://m.media-amazon.com/images/I/81GlRvn7R5L._AC_UL640_QL65_.jpg",
        inCart: 0,
    },
    {
        id: 3,
        title: "IFB 6 Kg 5 Star Fully Automatic Front Loading Washing Machine (Diva Aqua SX, Silver, Express wash)",
        price: 2599,
        rating: "4",
        img: "https://images-eu.ssl-images-amazon.com/images/I/41wCa2TCJ2L._AC_SX368_.jpg",
        inCart: 0,
    },
    {
        id: 4,
        title: "Samsung 28 L Convection Microwave Oven (MC28H5013AK/TL, Black)",
        price: 599,
        rating: "4",
        img: "https://m.media-amazon.com/images/I/71E6YcXfUcL._AC_UL640_QL65_.jpg",
        inCart: 0,
    },
    {
        id: 5,
        title: "Samsung 23 L Solo Microwave Oven (MS23J5133AG/TL, Black)",
        price: 899,
        rating: "4",
        img: "https://m.media-amazon.com/images/I/610VIYpm+FL._AC_UL640_QL65_.jpg",
        inCart: 0,
    },
    {
        id: 6,
        title: "Amazon Brand - Solimo 3-Door Foldable Wardrobe, 10 Racks, Brown",
        price: 1099,
        rating: "5",
        img: "https://m.media-amazon.com/images/I/91OM2TIgMRL._AC_UL640_QL65_.jpg",
        inCart: 0,
    },
    {
        id: 7,
        title: "Amazon Brand - Solimo Swerve Height Adjustable Laptop & Utility Table (Sandalwood)",
        price: 2299,
        rating: "4",
        img: "https://m.media-amazon.com/images/I/61Jq6POhncS._AC_UL640_QL65_.jpg",
        inCart: 0,
    },
];

export default Prods;
